#!/bin/sh
###############################################################################
# Copyright (C) 2026 by Donghun Jeong. All right reserved.
#
# Basic Information
# |--------------|----------------------------------------------------------|
# | File Name    | ctags-runtime                                            |
# |--------------|----------------------------------------------------------|
# | Description  | Select a version-specific repository Ctags profile      |
# |--------------|----------------------------------------------------------|
# | Author       | Donghun Jeong(dounghun22)                                |
# |--------------|----------------------------------------------------------|
# | Created      | 2026-08-09                                               |
# |--------------|----------------------------------------------------------|
# | Last Modified| 2026-08-09 11:36:07                                     |
# |--------------|----------------------------------------------------------|
#
# Revision History
# |-------------------------------------------------------------------------|
# |      Date     |                    Revision Summary                     |
# |---------------|---------------------------------------------------------|
# |   2026-08-09  | Added implementation detection and profile isolation.   |
# |---------------|---------------------------------------------------------|
#
# TODO, FIXME, NOTE
# CODEX ADDED: 2026-08-09 11:31:41 KST. Select one isolated explicit profile.
# CODEX MODIFIED: 2026-08-09 11:36:07 KST. Isolate the implementation probe.

###############################################################################

set -eu

FUN_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd -P)
RUNTIME_DIR=$(dirname -- "$FUN_DIR")
CTAGS_BIN=${CTAGS:-ctags}

if ! VERSION_OUTPUT=$(env -u CTAGS "$CTAGS_BIN" --options=NONE --version 2>/dev/null); then
    printf '%s\n' \
        "ctags-runtime: failed to probe Ctags executable '$CTAGS_BIN' with --version" >&2
    exit 1
fi

FIRST_LINE=$(printf '%s\n' "$VERSION_OUTPUT" | sed -n '1p')
case $FIRST_LINE in
    'Universal Ctags'*)
        PROFILE=$RUNTIME_DIR/ctags/ctags-universal.ctags
        ;;
    'Exuberant Ctags'*)
        PROFILE=$RUNTIME_DIR/ctags/ctags-exuberant.ctags
        ;;
    *)
        printf '%s\n' \
            "ctags-runtime: unsupported Ctags implementation from '$CTAGS_BIN': $FIRST_LINE" >&2
        exit 1
        ;;
esac

exec env -u CTAGS "$CTAGS_BIN" --options=NONE --options="$PROFILE" "$@"
